export interface ContainerTracking{
  id: number,
  articleOrdered: [],
  circuit: string,
  clearance: number,
  co: string,
  containerNumber: string,
  containerType: string,
  declaration: string,
  deliveryNoteNumber: string,
  deliveryNoteStatus: string,
  expectedDeliveryDate: Date,
  invoiceNumber: string,
  laodingDate: Date,
  puttingIntoUse: string,
  quantity: number,
  released: string,
  sentTo: string,
  shipper: string,
  status: string,
  totalValueWithFret: number,
  totalValueWithoutFret: number,
  transit: string,
  ve: string,
  vw: string
}