export enum ArticleAuthorityEnum {
    ARTICLE_ADD = "article:add",
    ARTICLE_UPDATE = "article:update",
    ARTICLE_LIST = "article:list",
    ARTICLE_STOCK_VALUE = "article:stock_value",
    ARTICLE_PURCHASE_VALUE = "article:stock_purchase_value",
    ARTICLE_SALE_VALUE = "article:stock_sale_value",
    ARTICLE_EXPORT_DATA = "article: exporte_to_excel",
    ARTICLE_COST_PRICE = "article:cost_price",
    ARTICLE_CUMP = "article:cump",
    ARTICLE_STOCK_QTY = "article:stock_qty",
    ARTICLE_CATALOGUE = "article:catalogue",
    ARTICLE_CUSTOMER_CATALOGUE = "article:customer_catalogue",
    ARTICLE_CUSTOMER_CATALOGUE_BY_FAMILY = "article:customer_catalogue_by_family",
    ARTICLE_STOCK_STATE = "article:stock_state",
    ARTICLE_UPDATE_SALE_PRICE = "article:update_sale_price",
    ARTICLE_DELETE = "article:delete", 
    ARTICLE_ACCESS_SUPER_DEALER_PRICE = "article:super_dealer_price",
    ARTICLE_ACCESS_GROSSISTE_PRICE ="article:grossiste_price",
    ARTICLE_ACCESS_DEMI_GROSSISTE_PRICE ="article:demi_grossiste_price", 
    ARTICLE_ACCESS_SHOWROOM_PRICE ="article:showroom_price",
    ARTICLE_CHANGE_SALE_PRICE ="article:change_sale_price",
    ARTICLE_ACCESS_QTY_SALE ="article:qty_sale",
    ARTICLE_DELETE_IMAGE = "article:delete_image"
}